version: "3"

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      - PORT=8080
      - DB_USER=testuser
      - DB_PASS=password
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=study_arc_development
    command: go run .
    ports:
      - "8080:8080"
    security_opt:
      - seccomp:unconfined # For Deleve debugger
    volumes:
      - .:/go/src/github.com/simiken/golang-cleanarchitecture:cached
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=password
  test:
    image: golang-cleanarchitecture_api
    environment:
      - PORT=8080
      - DB_USER=testuser
      - DB_PASS=password
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=study_arc_test
    command: go test -v ./...
    security_opt:
      - seccomp:unconfined # For Deleve debugger
    volumes:
      - .:/go/src/github.com/simiken/golang-cleanarchitecture:cached
    depends_on:
      - db
